### ISSUE TITLE
Die Extension geht sein ein paar Tagen nicht mehr 

### ISSUE THREAD

**Issue by hartmood** [jgoldhammer/moneymoney-payback#4]
Hallo,

wird das Projekt noch weiter geführt? Leider läuft die Extension seit kurzem nicht mehr. 

Viele Grüße
Hartmut

**Comment by jgoldhammer** [comment]
Duplikat von #3 . Durch die Umstellung muss ich prüfen, ob es weiterhin möglich ist.
