### ISSUE TITLE
Bugreport

### ISSUE THREAD

**Issue by CodigoBrew** [jgoldhammer/moneymoney-payback#5]
Dear Developer,

the update of the Payback balance permanently fails for some weeks now with error-message
"Payback-Punkte.lua:240: bad argument #1 to 'request' (string expected, got no value)"

Regards
Clemens

1> Session initialization completed successfully.
          1> Login successfull...
          1> Lade Kontostand und Umsätze für Paypack ...
          1> Getting transactions since 05.05.2019...
          1> Fill in date ranges
          1> Submitting transaction search form for ###MORENUMBERS###
          1> Payback-Punkte.lua:240: bad argument #1 to 'request' (string expected, got no value)

**Comment by christophbach** [comment]
Equal to #3 
Payback has made several changes to its website.

**Comment by jgoldhammer** [comment]
Closing in favor of #3
